USE [master]
GO
/****** Object:  Database [ZooDB]    Script Date: 25-Nov-19 5:02:54 PM ******/
CREATE DATABASE [ZooDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ZooDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ZooDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ZooDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ZooDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [ZooDB] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ZooDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ZooDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ZooDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ZooDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ZooDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ZooDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ZooDB] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [ZooDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ZooDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ZooDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ZooDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ZooDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ZooDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ZooDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ZooDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ZooDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ZooDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ZooDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ZooDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ZooDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ZooDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ZooDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ZooDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ZooDB] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ZooDB] SET  MULTI_USER 
GO
ALTER DATABASE [ZooDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ZooDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ZooDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ZooDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ZooDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ZooDB] SET QUERY_STORE = OFF
GO
USE [ZooDB]
GO
/****** Object:  Table [dbo].[Animal]    Script Date: 25-Nov-19 5:02:54 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Animal](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[location]    Script Date: 25-Nov-19 5:02:54 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[location](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[location] [nvarchar](50) NULL,
 CONSTRAINT [PK_location] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ZooAnimal]    Script Date: 25-Nov-19 5:02:54 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ZooAnimal](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ZooId] [int] NOT NULL,
	[AnimalId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ZooAnimal]  WITH CHECK ADD  CONSTRAINT [AnimalFK] FOREIGN KEY([AnimalId])
REFERENCES [dbo].[Animal] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ZooAnimal] CHECK CONSTRAINT [AnimalFK]
GO
ALTER TABLE [dbo].[ZooAnimal]  WITH CHECK ADD  CONSTRAINT [ZooFK] FOREIGN KEY([ZooId])
REFERENCES [dbo].[location] ([id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[ZooAnimal] CHECK CONSTRAINT [ZooFK]
GO
USE [master]
GO
ALTER DATABASE [ZooDB] SET  READ_WRITE 
GO
